import { GoogleGenAI, Type } from "@google/genai";
import {
  AIAnalysis,
  AIAnalysisSchema,
  AnalysisV2,
  AnalysisV2Schema,
  Color,
  EvaluateResponse,
  EvaluateResponseSchema,
} from '../../../shared/types/index.js';
import { isReplicateAvailable, removeBackground } from './replicateService.js';

// ──────────────────────────────────────────────────────────────────────
// Model IDs (centralised so we can swap providers in one spot).
// ──────────────────────────────────────────────────────────────────────
const MODEL_IMAGE_EDIT   = 'gemini-3.1-flash-image-preview';  // Stylize (image → image)
const MODEL_VISION_JSON  = 'gemini-3-flash-preview';          // Analyze + Evaluate (vision → JSON)
// Legacy text→image path kept for the existing /api/ai/generate-image route.
const MODEL_TEXT_TO_IMG  = 'gemini-2.5-flash-image';

let aiInstance: GoogleGenAI | null = null;
function getAI() {
  if (!aiInstance) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error('GEMINI_API_KEY environment variable is not set.');
    aiInstance = new GoogleGenAI({ apiKey });
  }
  return aiInstance;
}

// ──────────────────────────────────────────────────────────────────────
// Text-to-image (existing, kept for /api/ai/generate-image)
// ──────────────────────────────────────────────────────────────────────

function buildImagePrompt(userPrompt: string, paletteColors?: Color[]): string {
  let colorHint = '';
  if (paletteColors && paletteColors.length > 0) {
    const hexList = paletteColors.slice(0, 15).map((c) => c.hex).join(', ');
    colorHint = `\n- Preferred colour palette: ${hexList}`;
  }

  return `Create a pixel art image suitable for perler bead crafting.

Subject: ${userPrompt}

Requirements:
- Low resolution pixel art style (like a 32x32 or 48x48 sprite)
- Hard pixel edges with NO anti-aliasing, NO gradients, NO soft shadows
- Bold black (#000000) outlines clearly separating each colour region
- Flat solid colour fills within each region
- White (#FFFFFF) background
- Simple recognisable shapes, minimal fine detail
- Each colour region should be at least 3x3 pixels${colorHint}`;
}

export async function generateImageFromPrompt(
  prompt: string,
  paletteColors?: Color[],
): Promise<string> {
  const ai = getAI();
  const fullPrompt = buildImagePrompt(prompt, paletteColors);

  let response;
  try {
    response = await ai.models.generateContent({
      model: MODEL_TEXT_TO_IMG,
      contents: [{ text: fullPrompt }],
      config: { responseModalities: ['TEXT', 'IMAGE'] },
    });
  } catch {
    console.log(`[AI] ${MODEL_TEXT_TO_IMG} failed, falling back to ${MODEL_IMAGE_EDIT}...`);
    response = await ai.models.generateContent({
      model: MODEL_IMAGE_EDIT,
      contents: [{ text: fullPrompt }],
      config: { responseModalities: ['TEXT', 'IMAGE'] },
    });
  }

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
    }
  }
  throw new Error('No image was generated by the model');
}

// ──────────────────────────────────────────────────────────────────────
// V1 analyzer — retained for backwards compatibility with the old
// /api/ai/analyze endpoint. New pipeline uses analyzeDesignV2 instead.
// ──────────────────────────────────────────────────────────────────────

export async function analyzeDesignIntent(
  prompt: string,
  imageData?: string,
): Promise<AIAnalysis> {
  const ai = getAI();

  const response = await ai.models.generateContent({
    model: MODEL_VISION_JSON,
    contents: imageData
      ? [
          { text: `Analyze this image for a perler bead pattern. User request: ${prompt}. Return a structured design specification as JSON.` },
          { inlineData: { mimeType: 'image/png', data: imageData.replace(/^data:image\/\w+;base64,/, '') } },
        ]
      : [{ text: `Create a perler bead pattern specification for: ${prompt}. Return a structured design specification as JSON.` }],
    config: {
      responseMimeType: 'application/json',
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          subject: { type: Type.STRING },
          style: { type: Type.STRING },
          recommended_palette_family: { type: Type.STRING },
          recommended_max_colors: { type: Type.NUMBER },
          focus_regions: { type: Type.ARRAY, items: { type: Type.STRING } },
          simplification_rules: { type: Type.ARRAY, items: { type: Type.STRING } },
          notes: { type: Type.STRING },
        },
        required: [
          'subject', 'style', 'recommended_palette_family',
          'recommended_max_colors', 'focus_regions', 'simplification_rules', 'notes',
        ],
      },
    },
  });

  return AIAnalysisSchema.parse(JSON.parse(response.text || '{}'));
}

// ──────────────────────────────────────────────────────────────────────
// V2: Stylize — image → styled image + structured analysis
// ──────────────────────────────────────────────────────────────────────

export type StyleKey = 'cartoon' | 'pixel-realistic';

/**
 * Shape of what Gemini returns in its JSON part. Decoupled from AnalysisV2
 * because Gemini's schema enforcement uses its own type system (Type.OBJECT
 * etc.) — we parse and massage here.
 */
const STYLIZE_ANALYSIS_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    subject: { type: Type.STRING },
    keyFeatures: { type: Type.ARRAY, items: { type: Type.STRING } },
    paletteSubset: { type: Type.ARRAY, items: { type: Type.STRING } },
    skinBbox: {
      type: Type.ARRAY,
      items: { type: Type.NUMBER },
      description: 'Optional 4-number bbox [x,y,w,h] normalised 0-1. Include only if a face/skin region is present.',
    },
    eyeBboxes: {
      type: Type.ARRAY,
      items: { type: Type.ARRAY, items: { type: Type.NUMBER } },
      description: 'Optional array of [x,y,w,h] bboxes, 0-1 normalised.',
    },
    focusRegions: { type: Type.ARRAY, items: { type: Type.STRING } },
    autoTools: {
      type: Type.OBJECT,
      properties: {
        greyRemoval: { type: Type.BOOLEAN },
        outlineReinforce: { type: Type.BOOLEAN },
        colorSimplify: { type: Type.BOOLEAN },
        skinProtect: { type: Type.BOOLEAN },
        eyeEnhance: { type: Type.BOOLEAN },
        featureProtect: { type: Type.BOOLEAN },
      },
      required: ['greyRemoval', 'outlineReinforce', 'colorSimplify', 'skinProtect', 'eyeEnhance', 'featureProtect'],
    },
    tuningSeeds: {
      type: Type.OBJECT,
      properties: {
        edgeBias: { type: Type.NUMBER },
        minRegion: { type: Type.NUMBER },
        mergeThreshold: { type: Type.NUMBER },
        greyTolerance: { type: Type.NUMBER },
      },
      required: ['edgeBias', 'minRegion', 'mergeThreshold', 'greyTolerance'],
    },
    notes: { type: Type.STRING },
  },
  required: ['subject', 'keyFeatures', 'paletteSubset', 'autoTools', 'tuningSeeds', 'notes'],
};

function buildPixelArtPrompt(canvasSize: number, paletteHexes: string[]): string {
  const hexList = paletteHexes.slice(0, 20).join(', ');
  const blockPx = Math.max(4, Math.floor(1024 / canvasSize));
  // Compact prompt — the earlier 280-word version over-constrained Gemini
  // and suppressed its native "perler pattern" prior (see R3.95 plan).
  // Lead with the domain keyword ("perler-bead / 拼豆图纸") to activate the
  // right training distribution; make the eye=pupil+sclera rule explicit
  // because otherwise the pupil alone can't survive the grid without a
  // white ring around it; keep hard "no grid lines / no gradients"
  // constraints because Gemini WILL draw literal grid lines otherwise.
  return `Design a NEW kawaii-style pixel-art perler bead pattern chart (拼豆图纸) of the single main subject shown in the reference image.

This is a DESIGN task, not a photo edit. Your output is a FRESH chart drawing — think of the clean pixel-art style of capybara / Stitch / Pokémon perler charts shared online: chunky flat-colour blocks, 1-block-thick outlines, rounded stepped corners, small curated palette. Do NOT preserve the reference image's rendering (shading, gradients, textures, fine details). Keep ONLY the subject's identity and key signature colours.

THE SUBJECT (critical — read carefully):
Pick the SINGLE most prominent living character (person, animal, mascot) as THE subject. If multiple characters are present, pick the largest / most-centred one. If the reference has no living character (e.g. logo, food, object), treat the largest / most-centred OBJECT as the subject.

DRAW ONLY THE MAIN SUBJECT — its body, its clothing, and any small item it is actively holding or touching with its hands/body (e.g. a book in its hand, a phone it's looking at). This is the "lenient" rule: preserve the subject's pose and the one or two items directly in its grip.

DO NOT DRAW secondary elements, even if they're visually interesting:
- Floating decorative objects (clouds, sparkles, stars, bubbles, text, speech bubbles)
- Background scenery (sky, furniture, rooms, walls, floors, ground shadows)
- Other figures or characters in the scene
- Free-floating props not in the subject's hand (books, globes, phones, cars, balloons, etc. drifting around the subject)
- Duplicated / ghosted accessories
If an object is floating in mid-air and NOT being held → cut it. If it's resting on a surface near the subject → cut it.

NEGATIVE SPACE:
Outside the subject's silhouette, the canvas is PURE WHITE #FFFFFF. No floating objects, no decorative marks, no shadows, no scene. Treat the subject as if cleanly cut out and placed on a blank page.

Style: flat pixel-art with chunky solid-colour blocks, hard step edges, pure white (#FFFFFF) background, subject fills ~75% of the canvas and is centred.

Resolution target: roughly ${canvasSize} blocks across the longer side, each block ≈ ${blockPx}×${blockPx} output pixels. Anything smaller than 1 block will vanish when sampled into beads, so:

EYE CONSTRUCTION:
Each eye must be at least 2×2 blocks of dark pupil, plus a 1-block pure-white shine highlight INSIDE or touching the pupil's upper-left. The highlight must be a full-block white square — a 2-3 pixel speck will vanish at this resolution.

SCLERA RULE — STRICT: Only add a ring of white AROUND the pupil (sclera) if the REFERENCE IMAGE CLEARLY SHOWS visible eye whites around the pupil (wide-open anime/human eyes, doll eyes with visible whites). For characters with SOLID DARK EYES — Pikachu, Snoopy, most Pokémon, most mascots, Stitch, capybara — DO NOT draw sclera. The eye is JUST the dark pupil + the 1-block highlight inside it. Adding sclera where the reference has none makes the character look wrong ("googly eyes" problem).

If the reference has tiny, half-closed, squinting, or anime-dot-style eyes, enlarge the PUPIL to the 2×2 minimum — do NOT "fix" it by adding sclera. Pupil-only enlargement preserves character identity.

Other features:
- Mouth / nose / cheek blush / defining facial features: ≥ 2×2 blocks.
- Outlines: EXACTLY 1 block thick — never 2, never thicker even at dark silhouette edges or corners. Continuous and unbroken, using the ORIGINAL outline colour (black stays black — never dark green, never dark brown).

FLAT BODY COLOURS (critical — avoid "color speckle" in bead output):
The subject's body MUST use the smallest possible number of flat fills. Each body region (torso, head, limbs, ears) is ONE UNIFORM BLOCK COLOUR — no shading variations, no mid-tone highlights, no darker shadow cells along edges, no scattered lighter/darker pixels for "texture". A Pikachu body = ONE yellow only, not yellow + orange shadow + tan highlight. A blue hoodie = ONE blue only. Shading is FAILURE. Even a single misplaced lighter/darker block breaks into a visible speckle in the final pattern.

FACE & HAIR (critical for human / humanoid subjects):
- The face skin region is ONE FLAT colour. NO shadows cast by hair onto the face. NO darker skin patches for shading. NO hair wisps or stray dark strands crossing onto the skin area.
- Hair-face boundary is a clean 1-block BLACK outline (or the hair's natural dark outline colour). Hair sits ON TOP of the face cleanly — it does NOT bleed, gradient, or drop-shadow into the skin.
- Both eyes must be placed on CLEAN SKIN (not on hair, not on shadow). If the reference has hair hanging over an eye, REPOSITION hair so both eyes are fully visible on skin.
- Symmetry: both eyes must be the SAME size and SAME style. A tiny eye + a big eye = failure.

HELD GADGETS / SCREENS:
If the subject is holding a phone, tablet, laptop, book, or similar device, DRASTICALLY simplify its screen/face. At this resolution detailed UI (icons, text, app grids, photos on screen) becomes unreadable rainbow noise. Collapse the screen to:
- ONE flat background colour (white, sky blue, or dark blue), AND
- AT MOST 2-3 chunky solid-colour icons or shapes (each ≥ 2×2 blocks).
- NO small text, NO detailed illustrations on screen, NO colourful icon grids.
Same rule applies to patterns on the subject's clothing — simplify dense patterns to 1-2 flat colour zones.

Colours: keep the subject's ORIGINAL palette. The palette hex list below is a soft hint, NOT a constraint — do not recolour the subject to fit it. Aim for 10–15 flat tones total.
Reference hexes: ${hexList}

Hard constraints:
- Do NOT include ANY secondary elements from the reference (see SUBJECT rules above).
- Do NOT draw any grid lines, rulers, crosshairs, borders, labels, or reference markings over the image.
- Do NOT use gradients, soft shading, blurs, or anti-aliasing — every colour region is ONE flat fill with hard transitions.

Return only the redrawn image.`;
}

export interface StylizeResult {
  stylizedImageBase64: string;
  analysis: AnalysisV2;
  imageOk: boolean;     // false → stylize failed, image is the original
  analysisOk: boolean;  // false → analysis failed, fields are defaults
}

/**
 * Edit an input image into a bead-ready stylised version AND analyse it.
 *
 * Implementation note — must split into two parallel calls:
 *   - Image-edit model (3.1-flash-image-preview) returns inline image; it
 *     *cannot* simultaneously emit a JSON-schema-bound text part. Trying
 *     to combine `responseModalities: ['IMAGE','TEXT']` with
 *     `responseMimeType: 'application/json'` causes the model to suppress
 *     the image and only return JSON.
 *   - Vision-to-JSON model (3-flash-preview) gives us strictly-typed
 *     analysis via responseSchema.
 *
 * Each call can fail independently → caller still gets a usable result.
 */
export async function stylizeImage(args: {
  imageBase64: string;
  canvasSize: number;
  userIntent?: string;
  paletteHexes: string[];
  /** @deprecated kept for backward-compat; prompt no longer branches on style. */
  style?: StyleKey;
}): Promise<StylizeResult> {
  const { imageBase64 } = args;
  const [imageRes, analysisRes] = await Promise.allSettled([
    callImageEdit(args),
    callAnalyze(args),
  ]);

  const imageOk = imageRes.status === 'fulfilled';
  const analysisOk = analysisRes.status === 'fulfilled';

  if (!imageOk) {
    console.warn('[geminiService] image-edit failed:', (imageRes as PromiseRejectedResult).reason);
  }
  if (!analysisOk) {
    console.warn('[geminiService] analyze failed:', (analysisRes as PromiseRejectedResult).reason);
  }

  // Stylized image (Gemini result, or original on failure)
  let stylizedImageBase64 = imageOk ? imageRes.value : imageBase64;

  // BG removal pass — Replicate RMBG-2.0. Gives us a real alpha channel so
  // the client doesn't have to guess where the background ends.
  // Skipped silently if REPLICATE_API_TOKEN is missing or the call fails.
  if (isReplicateAvailable()) {
    try {
      const t = Date.now();
      stylizedImageBase64 = await removeBackground(stylizedImageBase64);
      console.log(`[geminiService] RMBG ok (+${Date.now() - t}ms)`);
    } catch (e) {
      console.warn('[geminiService] RMBG failed, keeping non-transparent image:', (e as Error).message);
    }
  } else {
    console.log('[geminiService] REPLICATE_API_TOKEN not set — skipping RMBG');
  }

  return {
    stylizedImageBase64,
    analysis: analysisOk ? analysisRes.value : fallbackAnalysis(args.userIntent),
    imageOk,
    analysisOk,
  };
}

/** Image-edit only call. Returns base64 data URL. */
async function callImageEdit(args: {
  imageBase64: string;
  canvasSize: number;
  userIntent?: string;
  paletteHexes: string[];
}): Promise<string> {
  const ai = getAI();
  const { imageBase64, canvasSize, userIntent, paletteHexes } = args;

  const systemPrompt = buildPixelArtPrompt(canvasSize, paletteHexes);
  const userText = userIntent
    ? `Subject hint from user: "${userIntent}". Apply the rules above.`
    : `Apply the rules above to the attached image.`;

  const response = await ai.models.generateContent({
    model: MODEL_IMAGE_EDIT,
    contents: [
      { text: systemPrompt },
      { text: userText },
      {
        inlineData: {
          mimeType: 'image/png',
          data: imageBase64.replace(/^data:image\/\w+;base64,/, ''),
        },
      },
    ],
    config: { responseModalities: ['IMAGE', 'TEXT'] },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
    }
  }
  throw new Error('Gemini image-edit returned no image part.');
}

/** Analysis-only call. Strictly-typed JSON via responseSchema. */
async function callAnalyze(args: {
  imageBase64: string;
  canvasSize: number;
  userIntent?: string;
  paletteHexes: string[];
}): Promise<AnalysisV2> {
  const ai = getAI();
  const { imageBase64, canvasSize, userIntent, paletteHexes } = args;

  const prompt = `Analyse the attached image briefly to guide a ${canvasSize}x${canvasSize} perler-bead pattern conversion.

A minimal pipeline runs: pixel → palette mapping, plus three always-on
post-processes (outline thinning + eye catchlight + skin-colour guard).
Most autoTools stay FALSE — EXCEPT the two listed below.

=== eyeEnhance + eyeBboxes ===
Set \`eyeEnhance: true\` whenever the subject has visible eyes (character,
animal, doll, face) and populate \`eyeBboxes\` with ONE tight [x,y,w,h]
per eye, normalised 0-1. Each bbox encloses ONLY the pupil+sclera —
NOT the whole head. Two eyes side-by-side → two bboxes; profile / wink →
one; no eyes (logo, object) → empty array and eyeEnhance=false.

=== skinProtect + skinBbox ===
Set \`skinProtect: true\` ONLY when the subject has VISIBLE HUMAN SKIN whose colour reads as pink / cream / peach / tan / brown. The palette's skin entries are human-flesh tones ONLY — not yellow, green, blue, orange, or any other mascot/animal colour.

Set skinProtect: **FALSE** (and omit skinBbox) for:
- Pokémon, Pikachu, mascots, cartoon animals — their face is fur / fabric / chassis, not skin. Yellow Pikachu face ≠ skin.
- Animals (cats, dogs, frogs, etc.) regardless of how cute or face-like they look.
- Logos, objects, robots, vehicles, abstract subjects.
- Characters whose visible face area is NOT pink/cream/peach/tan/brown.

When in doubt: is the subject's visible face area coloured in a HUMAN skin tone? If NO → skinProtect=false.

If skinProtect=true, populate \`skinBbox\` as a SINGLE tight [x,y,w,h] covering ONLY the human skin region — exclude hair, hat, clothing collar, background. A too-loose bbox is worse than no bbox.

User intent: "${userIntent || 'none'}"
Available palette (hex hints): ${paletteHexes.slice(0, 30).join(', ')}

Return JSON with:
- subject         — short description (e.g. "orange cat")
- keyFeatures     — regions of interest, e.g. ["face", "ears"] (can be empty)
- paletteSubset   — 10-20 palette IDs that best match the image's colours
- eyeBboxes       — per rules above; array of [x,y,w,h] 0-1 normalised
- skinBbox        — per rules above; single [x,y,w,h] or omit
- focusRegions    — leave empty for now
- autoTools       — greyRemoval / outlineReinforce / colorSimplify /
                    featureProtect: ALL FALSE.
                    eyeEnhance: TRUE iff subject has visible eyes.
                    skinProtect: TRUE iff subject has visible face skin.
- tuningSeeds     — use { edgeBias: 0.30, minRegion: 2, mergeThreshold: 25, greyTolerance: 1.2 }
- notes           — one short sentence`;

  const response = await ai.models.generateContent({
    model: MODEL_VISION_JSON,
    contents: [
      { text: prompt },
      {
        inlineData: {
          mimeType: 'image/png',
          data: imageBase64.replace(/^data:image\/\w+;base64,/, ''),
        },
      },
    ],
    config: {
      responseMimeType: 'application/json',
      responseSchema: STYLIZE_ANALYSIS_SCHEMA,
    },
  });

  const raw = JSON.parse(response.text || '{}');
  // Normalise bboxes that arrive as plain arrays.
  if (Array.isArray(raw.skinBbox) && raw.skinBbox.length !== 4) delete raw.skinBbox;
  if (Array.isArray(raw.eyeBboxes)) {
    raw.eyeBboxes = raw.eyeBboxes.filter(
      (b: unknown) => Array.isArray(b) && (b as number[]).length === 4,
    );
  }
  return AnalysisV2Schema.parse(raw);
}

function fallbackAnalysis(userIntent?: string): AnalysisV2 {
  return {
    subject: userIntent || 'pattern',
    keyFeatures: [],
    paletteSubset: [],
    autoTools: {
      greyRemoval: false, outlineReinforce: false, colorSimplify: true,
      skinProtect: false, eyeEnhance: false, featureProtect: false,
    },
    tuningSeeds: { edgeBias: 0.35, minRegion: 3, mergeThreshold: 30, greyTolerance: 1.4 },
    notes: 'Gemini analyze failed; using defaults.',
  };
}

// ──────────────────────────────────────────────────────────────────────
// V2: Evaluate — grid image + subject → confidence + tuning hints
// ──────────────────────────────────────────────────────────────────────

const EVAL_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    confidence: { type: Type.NUMBER },
    issue: {
      type: Type.STRING,
      enum: ['too_grey', 'fragmented', 'lost_eyes', 'weak_edges', 'wrong_colors', 'unrecognizable'],
    },
    tuningHint: {
      type: Type.OBJECT,
      properties: {
        edgeBias: { type: Type.NUMBER },
        minRegion: { type: Type.NUMBER },
        mergeThreshold: { type: Type.NUMBER },
        greyTolerance: { type: Type.NUMBER },
      },
    },
    reason: { type: Type.STRING },
  },
  required: ['confidence', 'reason'],
};

/**
 * Score a bead-grid render against the original subject.
 * Used by the retry orchestrator — on low confidence, tuningHint feeds back
 * into Engine T for a second pass.
 */
export async function evaluateGrid(args: {
  gridPngBase64: string;
  subject: string;
  currentTuning: { edgeBias: number; minRegion: number; mergeThreshold: number; greyTolerance: number };
}): Promise<EvaluateResponse> {
  const ai = getAI();
  const { gridPngBase64, subject, currentTuning } = args;

  const prompt = `Given a perler-bead grid render and the original subject "${subject}".

Rate 0-1: does this render recognizably depict ${subject}?

If rating < 0.7, identify the SINGLE worst issue:
- too_grey          | too many neutral greys → raise greyTolerance (currently ${currentTuning.greyTolerance})
- fragmented        | speckled, too many islands → raise minRegion (currently ${currentTuning.minRegion})
- lost_eyes         | facial features gone → lower minRegion in eye region
- weak_edges        | outlines indistinct → raise edgeBias (currently ${currentTuning.edgeBias})
- wrong_colors      | colours shifted wrong hue → tighten paletteSubset
- unrecognizable    | cannot identify

Suggest one or two numeric tweaks as tuningHint (partial TuningSeeds).
Return JSON: { confidence, issue?, tuningHint?, reason }`;

  const response = await ai.models.generateContent({
    model: MODEL_VISION_JSON,
    contents: [
      { text: prompt },
      {
        inlineData: {
          mimeType: 'image/png',
          data: gridPngBase64.replace(/^data:image\/\w+;base64,/, ''),
        },
      },
    ],
    config: {
      responseMimeType: 'application/json',
      responseSchema: EVAL_SCHEMA,
    },
  });

  return EvaluateResponseSchema.parse(JSON.parse(response.text || '{}'));
}
